services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: biblioteca_db
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: biblioteca_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - biblioteca-net

  # Servicio de Aplicación PHP + Apache
  app:
    image: southamerica-east1-docker.pkg.dev/nexus-491112/biblioteca-php/app-biblioteca:v1
    build: .
    container_name: biblioteca_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - biblioteca-net
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: biblioteca_user
      DB_PASS: biblioteca_password
      DB_NAME: biblioteca_db

volumes:
  db_data:

networks:
  biblioteca-net:
    driver: bridge
